import { readFileSync, existsSync } from "node:fs";

import { packageFile, writeJsonArtifact } from "./artifacts";

const CLI_PACKAGE_JSON = packageFile("package.json");
const OUTPUT_PATH = packageFile(
  "src",
  "generated",
  "ast-grep-rule-schema.json"
);

// Read @ast-grep/cli version from package.json. It is a devDependency: the
// shipped CLI depends only on the per-platform binary packages, and this
// wrapper is kept solely as the version source for this script.
const packageJson = JSON.parse(readFileSync(CLI_PACKAGE_JSON, "utf8")) as {
  devDependencies?: Record<string, string>;
};
const rawVersion = packageJson.devDependencies?.["@ast-grep/cli"];
if (!rawVersion) {
  throw new Error(
    "@ast-grep/cli not found in packages/cli/package.json devDependencies"
  );
}

// Strip semver range prefix (^, ~, >=, etc.)
const version = rawVersion.replace(/^[^\d]*/, "");
const sourceUrl = `https://raw.githubusercontent.com/ast-grep/ast-grep/${version}/schemas/rule.json`;

console.log(`Fetching ast-grep rule schema for version ${version}...`);
console.log(`  URL: ${sourceUrl}`);

let response: Response;
try {
  response = await fetch(sourceUrl);
} catch (error) {
  throw new Error(
    `Failed to fetch schema: ${error instanceof Error ? error.message : String(error)}`
  );
}

if (!response.ok) {
  if (existsSync(OUTPUT_PATH)) {
    console.error("  Existing schema file preserved.");
  }
  throw new Error(
    `HTTP ${String(response.status)} fetching schema from ${sourceUrl}`
  );
}

const schema = (await response.json()) as Record<string, unknown>;

// Provenance, with NO timestamp. `ast-grep-upgrade.yml` runs this on every
// scheduled pass and hands the result to `vendor-pr.cjs`, which force-pushes
// the rolling branch only when the proposed files differ from what is already
// there. A wall-clock stamp made the artifact differ on every run, so an
// upstream that had not moved would still rewrite the branch daily, dismissing
// approvals and restarting CI over nothing. The version and URL are the whole
// provenance; `git log` has the date.
schema["$comment"] =
  `Generated by fetch-ast-grep-schema.ts from ast-grep v${version} (${sourceUrl})`;

await writeJsonArtifact(OUTPUT_PATH, schema);
console.log(`  Written to: ${OUTPUT_PATH}`);
